### ISSUE TITLE
Removes fallback fonts

### ISSUE THREAD

**Issue by xPaw** [ben-eb/postcss-font-family#1]
```diff
-font: 14px/20px "Segoe UI", Helvetica, Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol";
+font: 14px/20px "Segoe UI", Helvetica, Arial, sans-serif;
```

Segoe UI Emoji font is used to correctly render emoji characters on Windows when using Chrome, it should not be removed.

**Comment by ben-eb** [comment]
Hm, that is an interesting use case. Shouldn't the emoticon font go first in the stack though? So that the unused codepoints fall through to the other fonts?

**Comment by xPaw** [comment]
That's how GitHub does it on `body`, there's probably a good reason for it.

**Comment by ben-eb** [comment]
I'm unsure what to do next. Should I remove this behaviour, or should I put it behind a config option? I've seen instances where people have placed non-emoji font families after say, a `sans-serif` keyword, which obviously gets dropped by the browser. But I don't want to cause rendering issues for those who know what they are doing.

What would you recommend? :smiley:

**Comment by ben-eb** [comment]
This behaviour is now optional, & enabled by default since `1.2.0`. https://github.com/ben-eb/postcss-font-family#removeafterkeyword
